---
description: |-
  The configuration endpoint allows to read certain configuration parameters of the OpenProject instance.
  Note that there is no 1:1 relationship between this endpoint and the settings you can find in your settings.yml.

  For now this endpoint will only allow access to settings deemed useful for a client to know in general.

  As clients might rely on the combination of both, the system settings as well as the current user's preferences, the resource
  embeds the current user's preferences so client can fetch both with one request.

  | Link                | Description                                      | Type            | Nullable | Supported operations |
  |:-------------------:| ------------------------------------------------ | -------------   | -------- | -------------------- |
  | self                | The configuration                                | Configuration   |          | READ                 |
  | userPreferences     | The preferences of the current user              | UserPreferences |          | READ                 |

  ## Local Properties

  | Property                  | Description                                        | Type       | Condition                         | Supported operations |
  | :-----------------------: | -------------------------------------------------- | ---------- | --------------------------------- | -------------------- |
  | maximumAttachmentFileSize | The maximum allowed size of an attachment in Bytes | Integer    |                                   | READ                 |
  | perPageOptions            | Page size steps to be offered in paginated list UI | Integer[]  |                                   | READ                 |
name: Configuration
